export { HeroSection } from './HeroSection';
export { HeroSectionV2 } from './HeroSectionV2';
export { ProblemSection } from './ProblemSection';
export { AuswirkungSection } from './AuswirkungSection';
export { ZielgruppeSection } from './ZielgruppeSection';
export { LoesungSection } from './LoesungSection';
export { SystemablaufSection } from './SystemablaufSection';
export { PaketeSection } from './PaketeSection';
export { WebAppsSection } from './WebAppsSection';
export { KostenlosSection } from './KostenlosSection';
export { FinalCTASection } from './FinalCTASection';
export { default as LiveAPISection } from './LiveAPISection';
